apiVersion: v1
kind: Service
metadata:
  name: random-string-service
spec:
  selector:
    app: random-string-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer